SRCS=misc_sqlcmd_bot.c misc_sqlcmd_chan.c misc_sqlcmd_main.c misc_sqlcmd_memo.c misc_sqlcmd_mysql.c misc_sqlcmd_nick.c misc_sqlcmd_obj.c misc_sqlcmd_util.c
TARGET=misc_sqlcmd.dll

include ..\Makefile.sub.win32
