SRCS= core.c \
      commands.c \
      activate.c \
      help.c \
      list.c \
      reject.c \
      request.c \
      waiting.c \
      drop.c \
      cmd_meow.c \
      cmd_vhost.c \
      conf.c \
      regex_db.c \
      language.c \
      exempt_db.c \
      group.c

TARGET=vhost

include ../Makefile.sub

